### ISSUE TITLE
Size of the outer circle and the stick button

### ISSUE THREAD

**Issue by jaybkim1** [controlwear/virtual-joystick-android#10]
@makowildcat 

Hi, I have two things that I would like to ask.

1. Is there a way to decrease the size of the stick buttons (both outer circle and inner button)?

2. [Demo Project You Provided](https://github.com/controlwear/virtual-joystick-demo)
    custom:JV_fixedCenter="false" seems to be not working.
    I would like to make the stick button to stay where a user's last touch.

**Comment by makowildcat** [comment]
Hi @jaybkim1 

1. I updated the joystick to include some size feature, it works as a ratio of the total width/height. It is documented, have a look. By default it is 0.25 and 0.75 for the button and background, but you can decrease it as you want. However, it doesn't work for the background if it is an image (at least for now).
2. The fixedCenter behavior is correct, maybe the word is not enough explicit, I added a bit of documentation to explain it. In a couple of days, maybe this weekend, I will (except if you want to) add the feature for the button staying in the last coordinate.

Have a good day!

Damien

**Comment by makowildcat** [comment]
Here it is! 

I upload the auto re-center option! You can set it to false, then the button will stay to its last position (see documentation).

Have a good one,

Damien

**Comment by jaybkim1** [comment]
@makowildcat 

I took a look at the updates and it works perfectly.
Thank you so much for your time, sir. 
Have a wonderful day!
