### ISSUE TITLE
# Configuring angle and strength position

### ISSUE THREAD

**Issue by jaybkim1** [controlwear/virtual-joystick-android#11]
Hi,

Is it possible for you to add a function to control where users are able to set angle and strength?
In other words, users can configure positions of angle and strength on their needs.

For example, the image below angle 90 is currently positioned to the top, but i want angle 0 to be positioned to the top, and angle 90 to the right side of the circle.

![virtual-joystick](https://user-images.githubusercontent.com/20435620/27677634-586b83ee-5ced-11e7-8e22-0fcbebc4c24e.png)

**Comment by makowildcat** [comment]
Hi Jonny, 

Sorry for answering late, I'm pretty busy those days and I won't be able to look at it deeply in for the next few days. But you're on the right track to adapt it ! Indeed you can modify it exactly where you found it at getAngle(). 

`
private int getAngle() { 
  int angle = (int) Math.toDegrees(Math.atan2(mCenterY - mPosY, mPosX - mCenterX));
  return angle < 0 ? angle + 360 : angle; // make it as a regular counter-clock protractor
}
`

Or you can also do it in your app when you get the regular angle like this : 
`
public void onMove(int angle, int strength) {
  angle = 90 - angle; // just with this, you will get 0 on top and 90 on right, but the rest will be a bit weird, I guess you can handle it with some other trick and maybe just one "if"
}
`
I'll have a closer look probably end of july.
Have a good day!
Kindly,
Damien

**Comment by jaybkim1** [comment]
@makowildcat 

Thank you, sir.
I wonder why I could not think about changing the angle inside onMove method.
I will close it since this may be dumb question to ask.
