### ISSUE TITLE
JV_buttonSizeRatio in example issue

### ISSUE THREAD

**Issue by sikrinick** [controlwear/virtual-joystick-android#12]
Hi,
In example it is mentioned, that we can specify buttonSizeRatio as a float:
custom:JV_buttonSizeRatio="0.15"
When actually it is expected to receive a fraction, as it is mentioned in attrs.xml:
<attr name="JV_buttonSizeRatio" format="fraction"/>
Can you fix readme, plz?

**Comment by makowildcat** [comment]
Hello @sikrinick ,

Ups, my bad, I thought Android wouldn't mind writing a fraction like this!
I updated with the correct way ("15%").
Thanks a lot for noticing it!

Have a lovely day.

Damien
