### ISSUE TITLE
Setting Button position when onCreate()

### ISSUE THREAD

**Issue by jaybkim1** [controlwear/virtual-joystick-android#13]
Hello, I thank you again for making this awesome library.
(I thought I starred this, but i guess i haven't, so I just starred it!)

**Is there a way to set the position of the button to certain angle when app loads?**
As far as I know, there is no method that has the function to configure it.
I know joystick is usually configured to center, but my project requires to configure the button at 
90 degree.

**Also, to extend the above question, i just want to know if it is possible to set the button ONLY movable around the outer circle line?**

**Comment by makowildcat** [comment]
Hi @jaybkim1 
I added the feature to stick the button around the border. You can have a look.
I don't know yet to initialize the button angle properly. I let the issue open but I don't know when I will have time to do it.

**Comment by jaybkim1** [comment]
@makowildcat 
Thank you so much!

As i complied your library using gradle in my project, do you have to change the gradle version or is there another way that I could add the feature?

**Comment by jaybkim1** [comment]
I downloaded your library and import it as library, but I have the following error (image attached)

![error](https://user-images.githubusercontent.com/20435620/29012591-bf924d20-7b77-11e7-91e1-6233acab3ac0.PNG)

**Comment by makowildcat** [comment]
Hmm, maybe the attrs.xml was not updated therefore it does not recognize it. Anyway I updated the version to 1.6 to make it easier, so now you should get this feature just by updating your gradle.

**Comment by jaybkim1** [comment]
@makowildcat 

Works like a charm!

Thank you so much again, sir!
Hope you have a wonderful day!

I will close this issue.
