### ISSUE TITLE
Add property to lock for vertical or horizontal movement

### ISSUE THREAD

**Issue by AlexandrDavydov** [controlwear/virtual-joystick-android#14]
Hello, this is a create library.
I'm creating the rc car control app. Is it possible to create a new property for the view that will move the joystick only in one direction horizontal or vertical.

Thanks in advance

**Comment by makowildcat** [comment]
Hi @AlexandrDavydov 
It’s done. I updated to 1.7.0 with a new feature to limit the button’s movement to horizontal or vertical axe.
I added documentation.
Let me know if everything OK, I’ll let the issue open for a couple of weeks.
Kindly,
Damien

**Comment by AlexandrDavydov** [comment]
Hi @makowildcat 

It exactly what I needed. Thank you a lot.
The only issue is you made a typo in the setter method 

`public void getDirection(int direction)`

and in documentation you have different method name 

`setButtonDirection`

It's a minor fix =)

Again thank you a lot for this feature


Best Regards,
Alexander

**Comment by makowildcat** [comment]
Oups..
Thanks you a lot for your quick answer (and for the idea of the feature)!
I fixed the issue, it is now `version 1.7.1` with the real name `setButtonDirection` as in the documentation. :)
Kindly,
Damien

**Comment by AlexandrDavydov** [comment]
Good. All works fine. 
I think is time to close the issue.

My best wishes for you.
Thanks for your help.
Happy coding =)
