### ISSUE TITLE
When creating new joystick, R.id.joystickView returns cannot resolve symbol

### ISSUE THREAD

**Issue by mbuffery** [controlwear/virtual-joystick-android#17]
Unable to use joystick as it crashes the program each time. Since the new update, android doesnt need you to write " mTextViewAngle = (TextView) findViewById(R.id.textView_angle);" as its unnecessary casting though it breaks the program if i do so. Any ideas??

**Comment by SourceCodeDeleted** [comment]
@mbuffery  what happened here? Is there an update to this?
