### ISSUE TITLE
Lower minimal API level

### ISSUE THREAD

**Issue by esplemea** [controlwear/virtual-joystick-android#19]
Hello,
As I wanted to use the project, I noticed that the minimal API level is 19 but mine was set at 16. I believe you could just lower it without any drawback, or otherwise maybe specify that in the Readme.
Versions 16-18 represent around 5% of the users so I didn't want to set it to 19 (src: https://developer.android.com/about/dashboards/index.html)

(By the way, thanks for the joystick, I just downloaded the class directly and put the code instead, works great!)

**Comment by makowildcat** [comment]
Hello @esplemea 
Thank you very much for your feedback, indeed it seems to be working with API level 16. I downgraded the minimum level api, it is now 16 with the (now current) version 1.9.0 of the library.
Kindly,
Damien
(I'll let the issue open a couple of day just in case and I'll close it)

**Comment by FenixGit** [comment]
Hello @makowildcat 
I did a test and now continues the error with API 16

Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [io.github.controlwear:virtualjoystick:1.9.0] C:\Users\Fenix\.gradle\caches\transforms-1\files-1.1\virtualjoystick-1.9.0.aar\d5b64f282115f1220364385942a66bca\AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="io.github.controlwear.virtual.joystick.android" to force usage (may lead to runtime failures)

**Comment by makowildcat** [comment]
Hi @FenixGit 
Ups, my bad, sorry. I cleaned the build and upgraded some gradle files, tested it and now it should be ok with the 1.9.2. Thank you for you feedback too!
Damien
