### ISSUE TITLE
Border color alpha bug

### ISSUE THREAD

**Issue by AlexanderShniperson** [controlwear/virtual-joystick-android#21]
Hello

It looks like i found bug and haven't idea how to fix that.
Bug is related to setting Alpha for border color and at runtime it looks like Border object doubles itself, first with alpha and next one without alpha channel.
Steps to reproduce
```
        mPaintCircleBorder.setColor(borderColor);
        mPaintCircleBorder.setAlpha(125);

```

**Comment by makowildcat** [comment]
Hi @AlexanderShniperson 

Sorry for the late reply.
I fixed the issue, I am glad you noticed it! Thank you.
You should update to the version `1.9.3 `.

Also, now the easiest way to play with the border's alpha is to use:
`custom:JV_borderAlpha="128"` or `joystick.setBorderAlpha(128);`

Just in case, I'll close the issue in a couple of days.

Have a great day!
Kindly,
Damien
