### ISSUE TITLE
Change joystick position programmatically at run-time?

### ISSUE THREAD

**Issue by nathanRamaNoodles** [controlwear/virtual-joystick-android#26]
Is it possible to change the joystick's location from the java code?  I am planning on using a Bluetooth joystick to map to the virtual joystick on my phone.  But I'm unable to change the position of the joystick programmatically.  Is there a way for you to add a method for us to change the position programmatically?

Thanks for this great library :D

**Comment by IchZerowan** [comment]
I have managed to do this using RelativeLayout's margins, though I cannot currently get joystick working without touching screen for the second time

**Comment by nathanRamaNoodles** [comment]
I finished my app, and forgot to close this issue.  [Here's my finished work ](https://github.com/nathanRamaNoodles/Tinker-Controller):)

I decided to make my own joysticks from scratch.
