### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by lefuturiste** [controlwear/virtual-joystick-android#29]
I'm sorry but I can't manage to include this lib into my android project, can someone provide detailled instructions about the installation process?

**Comment by lefuturiste** [comment]
I finally managed to get this thing working. I will share the code later.

**Comment by WiccyShackleton** [comment]
> I finally managed to get this thing working. I will share the code later.

I have managed to import it as a module but i cannot find the joystick in the layout editor to place it :(

**Comment by LuisMiguelSS** [comment]
> 
> 
> > I finally managed to get this thing working. I will share the code later.
> 
> I have managed to import it as a module but i cannot find the joystick in the layout editor to place it :(

You should add in via text in the XML file of the Activity in which you want to use it

**Comment by ADdasuan** [comment]
> Мне наконец удалось заставить эту вещь работать. Я поделюсь кодом позже.

Can you share the code please. I'm just learning and therefore I don't understand how to use it

**Comment by lefuturiste** [comment]
hello @ADdasuan ,
you will find my implementation here:
https://github.com/lefuturiste/LYRC-control-android-app/

to sum up
I copied the file `JoystickView.java` from this repository into my code base
Then I used it in my XML like this

```xml
            <fr.werobot.lyrc_control_app.JoystickView xmlns:custom="http://schemas.android.com/apk/res-auto"
                android:id="@+id/joystick"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                custom:JV_backgroundColor="#009688"
                custom:JV_borderColor="#00796B"
                custom:JV_borderWidth="8dp"
                custom:JV_buttonColor="#FF6E40"
                custom:JV_buttonSizeRatio="15%"
                custom:JV_fixedCenter="false" />
 ```

And in my java code I fetched a `JoystickView` instance like this:

https://github.com/lefuturiste/LYRC-control-android-app/blob/b40888a9d99ddeac910ce0522bebb92f18a21c89/app/src/main/java/fr/werobot/lyrc_control_app/GameOldFragment.java#L152

These are some insights.
