### ISSUE TITLE
Change DEFAULT_LOOP_INTERVAL

### ISSUE THREAD

**Issue by Ka-Repo** [controlwear/virtual-joystick-android#33]
The DEFAULT_LOOP_INTERVAL is too fast for my Arduino.

Is it possible to increase this value? File JoystickView.java is read only?

**Comment by jobeljohny** [comment]
is it resolved? how did you manage to send data from your android to Arduino?

**Comment by Ka-Repo** [comment]
yes, it´s resolved.

I needed to adjust the refresh rate of the joystick, the event listener takes it as last argument

joystick.setOnMoveListener( .. , refreshRateInMillisec);
