### ISSUE TITLE
Allow JotstickView to be disabled

### ISSUE THREAD

**Issue by djjaysmith** [controlwear/virtual-joystick-android#6]
Hi,

This is a great class and just what I was looking for, thanks.  But I do have one issue where it is not currently not possible to disable to JoystickView.

It would be good to be able to call `joystickView.setEnabled(false)` so that the view can not be used at all.  So that it cannot be moved and `onMove()` is not called.

DJ

PS.  A simple demo app would also have been good in getting started.

**Comment by makowildcat** [comment]
Hi @djjaysmith 
Excellent idea! I will do it this weekend, both the simple demo app and the “enabled” feature!
I’ll let you know when it is done.
Damien

**Comment by makowildcat** [comment]
Tadaaa!
I did it (sorry, a bit late...) :) You can have a look!
I let the issue open few days, let me know if anything wrong.
Damien

**Comment by jaybkim1** [comment]
@makowildcat 

Hi, I have two things that I would like to ask.

1. Is there a way to decrease the size of the stick button?

2. [Demo Project You Provided](https://github.com/controlwear/virtual-joystick-demo)
    custom:JV_fixedCenter="false" seems to be not working.
    I would like to make the stick button to stay where a user's last touch.
