### ISSUE TITLE
How do i include this file in my project?

### ISSUE THREAD

**Issue by rtm516** [controlwear/virtual-joystick-android#7]
I have tried copying the file into my project and it says "Package R does not exist" and i cant build.

Thanks in advance.

**Comment by djjaysmith** [comment]
No need for a local copy, just include 

> compile 'io.github.controlwear:virtualjoystick:1.2.0'

in your build.gradle file in the dependencies list

**Comment by makowildcat** [comment]
Hi @rtm516 

I hope, the @djjaysmith 's answer (by the way thank you) fix your problem, it should.

Damien
