### ISSUE TITLE
How Do I Deal With Attributes?

### ISSUE THREAD

**Issue by jaybkim1** [controlwear/virtual-joystick-android#8]
I put `compile 'io.github.controlwear:virtualjoystick:1.2.0'` in my build.gradle, and

I have the following code in my activity_main.xml
```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorAccent"
    tools:context="com.example.jayb.joystickexample.MainActivity">

    <TextView
        android:id="@+id/angle"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="angle:"
        android:layout_alignParentTop="true"
        android:layout_alignParentStart="true"
        android:layout_marginStart="59dp"
        android:layout_marginTop="34dp" />

    <TextView
        android:id="@+id/strength"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="strength:"
        android:layout_below="@+id/angle"
        android:layout_marginStart="59dp"
        android:layout_marginTop="10dp"
        />

 <io.github.controlwear.virtual.joystick.android.JoystickView
        android:id="@+id/joystickView"
        android:layout_width="200dp"
        android:layout_height="200dp"
        android:layout_marginBottom="122dp"
        android:layout_alignParentBottom="true"
        android:layout_centerHorizontal="true"
        custom:JV_buttonColor="#FF6E40"
        custom:JV_borderColor="#00796B"
        custom:JV_backgroundColor="#009688"
        custom:JV_borderWidth="4dp"
        custom:JV_fixedCenter="false"
        />
</RelativeLayout>

```
**I do not know how to deal with these lines of custom:JV_buttonColor, custom:JV_borderColor, custom:JV_backgroundColor, custom:JV_borderWidth, custom:JV_fixedCenter**

How do I deal with those attributes?

I am trying to make the same .xml(design) as below image. I tried to find the .xml in your project, but it seems like there isn't one.

![android-virtual-joystick-custom-image](https://cloud.githubusercontent.com/assets/20435620/26763858/cae0c094-4995-11e7-8b3b-2117cc6bd778.png)

**Comment by makowildcat** [comment]
Hello @jaybkim1 

You need to add `xmlns:custom="http://schemas.android.com/apk/res-auto"` to your RelativeLayout (or you can just add it to the JoystickView itself) and it should work! :)

Indeed there isn’t such file in this project because it is only the library, but in a couple of hours, I am going to upload a repository as a very simple example.

I hope it is going to be ok, have a good day!

Damien

**Comment by jaybkim1** [comment]
@makowildcat 
Thank you so much for a quick response. I really appreciate it. It will help me a lot to implement what my company wants me to develop, and I want to thank you again for creating a demo for those who would be struggling to find out how to utilize this library like me. 

It certainly helps me a lot !

**Comment by makowildcat** [comment]
My pleasure! I’m glad it helps :)
